jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t my-app:$IMAGE_TAG ./app
          docker tag my-app:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/my-app:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/my-app:$IMAGE_TAG

      - name: Deploy stack with new image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/my-app:${GITHUB_SHA::8}
          cdk deploy MyStack -c image_uri=$IMAGE_URI --require-approval never

 