name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd cdk
        pip install -r requirements.txt

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Run CDK synth
      run: |
        cd cdk
        cdk synth

    - name: Run contract tests
      run: PYTHONPATH=. pytest tests/contract/ -v

    - name: Run deployment tests
      run: |
        # This would run integration tests, but for CI we skip actual deployment
        echo "Skipping actual deployment in CI - would run post-deployment tests here"

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install Python dependencies
      run: |
        cd cdk
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy infrastructure
      run: ./scripts/deploy.sh